config/routes.rb
Rails.application.routes.draw do
  root 'columns#index'
  resources :columns, only: [:index]
  resources :tasks, only: [:new, :create, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/column.rb
class Column < ApplicationRecord
    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :column
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  def index
    @columns = Column.all
  end
end

app/controllers/tasks_controller.rb
# app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new 
    @task = Task.new
    @column_id = params[:column_id]
  end
  
  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      render json: @task
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :column_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/columns/index.html.erb
<div class="kanban-board">
  <% @columns.each do |column| %>
    <div class="column droppable" data-column-id="<%= column.id %>">
      <h2><%= column.name %></h2>
      <div class="tasks-container" data-column-id="<%= column.id %>">
        <% column.tasks.each do |task| %>
          <%= render 'tasks/task', task: task %>
        <% end %>
      </div>
      <%= link_to 'Add Task', new_task_path(column_id: column.id), class: 'add-task' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KanbanBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <%= f.hidden_field :column_id, value: @column_id %>
  <div class="form-field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <%= f.submit 'Create Task', class: "submit-btn" %>
<% end %>

app/views/tasks/_task.html.erb
<div class="task draggable" data-id="<%= task.id %>">
  <h3><%= task.title %></h3>
  <p><%= task.description %></p>
</div>

app/views/tasks/new.html.erb
<div class="new-task">
  <h1>New Task</h1>
  <%= render 'form', class: "task-form" %>
  <%= link_to 'Back', root_path, class: "back-link" %>
</div>